# functions for compute fields of modes corresponding to BICs

"""
    ModeField

Contain information of modes corresponding to BICs. 

# Fields
- `k::Float64`: the wavenumber
- `inn::Float64`: the dielectric constant inside the cylinders or air-holes
- `ext::Float64`: the dielectric constant outside the cylinders or air-holes
- `r::Float64`: the radius of the cylinders or air-holes
- `orders::Vector{Int64}`: the orders of Bessel functions and Neumann functions
- `coeffs::Matrix{Float64}`: the coefficients in the cylindrical expansion outside the cylinder, see [`get_coeff`](@ref)
- `expan_coeffs::Vector{ComplexF64}`: the coefficients before special functions
- `mode::Symbol`: the polarizations, supported types: `:te` or `:tm`
- `α::Float64`: the Bloch wavenumber, it is only nonzero for propagating BICs
"""
struct ModeField 
    k::Float64 
    inn::Float64
    ext::Float64
    r::Float64
    orders::Vector{Int64}
    coeffs::Matrix{Float64}
    expan_coeffs::Vector{ComplexF64}
    mode::Symbol
    α::Float64
end

"""
    compute_mode(sp::SamplingPoints, k, r, inn, ext, homo; α::Float64 = 0.0, mode::Symbol = :te, period::Float64 = 2π)

Compute the mode of a BIC at the wavenumber `k`.

# Arguments
- `sp`: the sampling points along the boundary of the square cell, generated by [`get_samplingpoints`](@ref)
- `k`: the wavenumber; it should be at (or very close to) the BIC frequency
- `r`: the radius of the cylinder (dielectric rod) or air hole
- `inn`: the dielectric constant inside the cylinder or air hole
- `ext`: the dielectric constant outside the cylinder or air hole
- `homo`: the dielectric constant of the homogeneous medium outside the periodic slab, used by the transparent boundary condition, see [`apply_tbc!`](@ref)

# Keyword Arguments
- `α`: the Bloch wavenumber, `α = 0` for standing BICs, `α ≠ 0` for propagating BICs
- `mode`: the polarization, `:te` or `:tm`, see [`get_coeff`](@ref)
- `period`: the period of the slab. It must equal the cell width of the square used to build `sp`

!!! note
    The field is determined only up to a constant factor inherited from the
    arbitrary normalization of the eigenvector. To evaluate the field on a
    grid, use [`evaluate_field`](@ref).

"""
function compute_mode(sp::SamplingPoints, k, r, inn, ext, homo; α::Float64 = 0.0, mode::Symbol = :te, period::Float64 = 2π)
    n = sp.n
    
    odrs = [j - 1 - 2n for j in 1:4n]

    cydc = build_cylinder_cache(4n, k, r, inn, ext)
    coef = get_coeff(4n, cydc, inn, ext, mode = mode)
    bydc = build_boundary_cache(sp, 4n, k, ext)
    Λ, A = assemble_dtn(sp, 4n, coef, bydc, k, ext; mode = mode, homo = homo)
    Δ = apply_bc(Λ, n; α = α, period = period)
    apply_tbc!(Δ, sp, k; α = α, homo = homo, period = period)
    
    evals, evecs = eigen(Δ)
    idx = argmin(abs.(evals))
    v = evecs[:, idx]
    
    # Reconstruct the Dirichlet data on 4 edges
    u = _reconstruct_dirichlet(v, n, α, period)
    
    c = A \ u

    return ModeField(k, inn, ext, r, odrs, coef, c, mode, α)
end

function _reconstruct_dirichlet(v, n, α, period)
    e⁺ = iszero(α) ? one(eltype(v)) : exp(im * α * period) 
    u = similar(v, 4n)
    
    copyto!(u, 1,   v, 1,   n)   # bottom edge
    copyto!(u, n+1, v, n+1, n)   # left
    copyto!(u, 2n+1, v, 2n+1, n) # top

    for j in 1:n
        u[3n + j] = e⁺ * v[2n + 1 - j] # right edge: reverse mirror of left with Bloch phase
    end
    
    return u
end

"""
    evaluate_field(mf::ModeField, xs, ys)
    evaluate_field(mf::ModeField, sq::Square, xs, ys)

Evaluate the field of `mf` on the grid given by `xs` and `ys`; `xs` varies along
the rows of the returned matrix.

The first method evaluates the field in the central cell only, where the
expansion was fitted. `xs` must lie within that cell (`|x| ≤ semi`); for points
outside it, use the second method.

The second method evaluates the field with Bloch continuation: each point is
folded into the cell of `sq` and multiplied by `exp(im*α*L*m)`, the phase of its
cell (`L = 2*sq.semi`). For `α = 0` this is the periodic repetition. The `Square`
must be the one that generated the sampling points used to build `mf`, i.e.
`period == 2*sq.semi`.

!!! note
    The field is determined up to a constant factor inherited from the
    arbitrary normalization of the eigenvector; see [`gauge_field!`](@ref) and
    [`normalize_field!`](@ref).
"""
function evaluate_field(mf::ModeField, xs, ys)
    field = zeros(ComplexF64, length(xs), length(ys))
    ki = mf.k * sqrt(mf.inn)
    ke = mf.k * sqrt(mf.ext)
    trunc = length(mf.orders)
    
    @inbounds for j in eachindex(ys)
        y = ys[j]

        for i in eachindex(xs)
            x = xs[i]
            rd = sqrt(x^2 + y^2)
            θ = atan(y, x)
        
            val = zero(ComplexF64)

            if rd < mf.r 
                for t in 1:trunc 
                    val += mf.expan_coeffs[t] * besselj(mf.orders[t], ki * rd) * exp(im * mf.orders[t] * θ)
                end
            else
                for t in 1:trunc
                    radial = mf.coeffs[1, t] * besselj(mf.orders[t], ke * rd) + mf.coeffs[2, t] * bessely(mf.orders[t], ke * rd)
                    val += mf.expan_coeffs[t] * radial * exp(im * mf.orders[t] * θ)
                end
            end
        
            field[i, j] = val
        end
    end

    return field
end

function evaluate_field(mf::ModeField, sq::Square, xs, ys)
    L = 2 * sq.semi
    ms = round.(Int, (xs .- sq.center[1]) ./ L)
    field = evaluate_field(mf, xs .-ms .* L,ys)
    field .*= exp.(im * mf.α * L .* ms)

    return field
end

# two post-processing utilities for plotting modes

"""
    normalize_field!(field) -> field

Normalize `field` to unit maximum modulus (max-norm), the usual convention for
comparing the fields of different modes.
"""
normalize_field!(field) = (field ./= maximum(abs, field); field)

"""
    gauge_field!(field) -> field

Rotate `field` by a global phase so that its imaginary part is as small as
possible. The optimal phase is `-arg(Σᵢ uᵢ²)/2`; the result is then flipped so
that its dominant entry is positive real.

For standing BICs (`α = 0`) the mode is real up to a phase, so `real.(field)`
after this transformation shows the standing-wave pattern, and the residual
imaginary part is numerical noise. For propagating BICs the field is genuinely
complex and no phase makes it real — plot `abs.(field)` instead, without gauging.
"""
function gauge_field!(field)
    a = sum(x -> x^2, field)                    # Σ uᵢ², phase-sensitive
    field .*= exp(-im * angle(a) / 2)
    i0 = argmax(abs, field)
    real(field[i0]) < 0 && (field .*= -1)
    return field
end